"""
Task Scheduler for AI Employee

Schedules and executes tasks at specified times using the schedule library.
"""
import time
import logging
import schedule
from pathlib import Path
from datetime import datetime, timedelta
import subprocess
import sys
import threading
from typing import Callable, Any

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s',
    handlers=[
        logging.FileHandler('Logs/scheduler.log'),
        logging.StreamHandler()
    ]
)
logger = logging.getLogger(__name__)

class TaskScheduler:
    """Manages scheduling and execution of automated tasks."""

    def __init__(self):
        self.active_jobs = []
        self.daemon_jobs = []  # For continuous running jobs
        self.scheduled_posts_dir = Path("Scheduled_Posts")
        self.needs_action_dir = Path("Needs_Action")
        self.logs_dir = Path("Logs")

        # Create necessary directories
        for dir_path in [self.scheduled_posts_dir, self.needs_action_dir, self.logs_dir]:
            dir_path.mkdir(exist_ok=True)

    def schedule_daily_tasks(self):
        """Schedule daily recurring tasks."""
        # Schedule daily status report
        daily_job = schedule.every().day.at("09:00").do(self.run_daily_status_report)
        self.active_jobs.append(daily_job)
        logger.info("Scheduled daily status report at 09:00")

        # Schedule daily inbox cleanup
        cleanup_job = schedule.every().day.at("23:00").do(self.run_daily_cleanup)
        self.active_jobs.append(cleanup_job)
        logger.info("Scheduled daily cleanup at 23:00")

        # Schedule LinkedIn posting
        linkedin_job = schedule.every().day.at("12:00").do(self.run_linkedin_posting)
        self.active_jobs.append(linkedin_job)
        logger.info("Scheduled LinkedIn posting at 12:00")

        # Schedule weekly audit
        weekly_job = schedule.every().sunday.at("22:00").do(self.run_weekly_audit)
        self.active_jobs.append(weekly_job)
        logger.info("Scheduled weekly audit at Sunday 22:00")

    def schedule_linkedin_posts(self):
        """Schedule automated LinkedIn posts."""
        # Schedule morning business tip
        morning_post = schedule.every().monday.at("09:00").do(self.post_morning_tip, "monday")
        self.active_jobs.append(morning_post)

        morning_post = schedule.every().tuesday.at("09:00").do(self.post_morning_tip, "tuesday")
        self.active_jobs.append(morning_post)

        morning_post = schedule.every().wednesday.at("09:00").do(self.post_morning_tip, "wednesday")
        self.active_jobs.append(morning_post)

        morning_post = schedule.every().thursday.at("09:00").do(self.post_morning_tip, "thursday")
        self.active_jobs.append(morning_post)

        morning_post = schedule.every().friday.at("09:00").do(self.post_morning_tip, "friday")
        self.active_jobs.append(morning_post)

        logger.info("Scheduled morning business tips for weekdays at 09:00")

    def run_daily_status_report(self):
        """Run daily status report task."""
        try:
            # Create a status report in the Needs_Action folder
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            report_filename = f"DAILY_STATUS_REPORT_{timestamp}.md"
            report_path = self.needs_action_dir / report_filename

            report_content = f"""---
type: daily_status_report
date: {datetime.now().strftime('%Y-%m-%d')}
status: pending
priority: low
---

# Daily Status Report
{datetime.now().strftime('%A, %B %d, %Y')}

## System Status
- **Time:** {datetime.now().strftime('%H:%M:%S')}
- **System Health:** Operational
- **Tasks Processed Yesterday:** [To be filled by system]
- **Pending Tasks:** [To be filled by system]

## Scheduled Tasks Today
- LinkedIn post at 12:00 PM
- Daily cleanup at 11:00 PM
- Status report at 9:00 AM (this report)

## System Metrics
- Files in Needs_Action: {len(list(self.needs_action_dir.glob('*.md')))}
- Active scheduled posts: {len(list(self.scheduled_posts_dir.glob('*.json')))}
- System running since: [Start time]

## Notes
This is an automatically generated daily report to track system operations.

---
*Generated by AI Employee Scheduler at {datetime.now().strftime('%H:%M:%S')}*
"""

            report_path.write_text(report_content)
            logger.info(f"Daily status report created: {report_filename}")

        except Exception as e:
            logger.error(f"Error running daily status report: {e}")

    def run_daily_cleanup(self):
        """Run daily cleanup tasks."""
        try:
            logger.info("Running daily cleanup...")

            # Archive old files (older than 30 days)
            cutoff_date = datetime.now() - timedelta(days=30)

            # Archive old log files
            logs_dir = Path("Logs")
            if logs_dir.exists():
                for log_file in logs_dir.glob("*.log"):
                    if log_file.stat().st_mtime < cutoff_date.timestamp():
                        archive_dir = logs_dir / "archive"
                        archive_dir.mkdir(exist_ok=True)
                        archived_file = archive_dir / log_file.name
                        log_file.rename(archived_file)
                        logger.info(f"Archived old log file: {log_file.name}")

            logger.info("Daily cleanup completed successfully")

        except Exception as e:
            logger.error(f"Error running daily cleanup: {e}")

    def run_linkedin_posting(self):
        """Run scheduled LinkedIn posting."""
        try:
            logger.info("Running scheduled LinkedIn posting...")

            # Example LinkedIn post content
            sample_post = f"""
Exciting update from our team!

Today we're focusing on maximizing efficiency through automation. Our AI Employee system continues to evolve, bringing you more automated business solutions.

#AI #Automation #BusinessGrowth #Productivity

---
Posted automatically by AI Employee system on {datetime.now().strftime('%A, %B %d, %Y')}
"""

            # Create a scheduled post request
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            post_filename = f"LINKEDIN_POST_{timestamp}.md"
            post_path = self.needs_action_dir / post_filename

            post_content = f"""---
type: linkedin_post_request
status: pending
priority: medium
scheduled_time: {datetime.now().isoformat()}
---

# LinkedIn Post Request

## Post Content
{sample_post}

## Actions Required
- [ ] Review post content
- [ ] Verify appropriate for LinkedIn audience
- [ ] Post to LinkedIn account
- [ ] Monitor engagement
- [ ] Update status when posted

## Guidelines
- Ensure post aligns with business goals
- Check for appropriate hashtags
- Verify company branding

---
*Generated by AI Employee Scheduler*
"""

            post_path.write_text(post_content)
            logger.info(f"LinkedIn post request created: {post_filename}")

        except Exception as e:
            logger.error(f"Error running LinkedIn posting: {e}")

    def post_morning_tip(self, day_of_week: str):
        """Post a morning business tip."""
        try:
            tips = {
                "monday": "Start your week right: Review and prioritize your top 3 goals for the week. Focus on what matters most!",
                "tuesday": "TIP: Automate repetitive tasks to save time for strategic thinking. What can you automate this week?",
                "wednesday": "Middle of the week check: Are you on track with your goals? Adjust as needed!",
                "thursday": "TIP: Take 10 minutes to organize your workspace. A clean environment enhances productivity!",
                "friday": "End your week strong: Plan your weekend strategically for a refreshed start to next week!"
            }

            tip = tips.get(day_of_week, "Weekly Business Tip: Focus on efficiency and growth!")

            # Create a morning tip post
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            tip_filename = f"MORNING_TIP_{day_of_week.upper()}_{timestamp}.md"
            tip_path = self.needs_action_dir / tip_filename

            tip_content = f"""---
type: morning_tip_post
status: pending
priority: medium
day_of_week: {day_of_week}
scheduled_time: {datetime.now().isoformat()}
---

# Morning Business Tip - {day_of_week.title()}

## Tip of the Day
{tip}

## Action Required
- [ ] Review tip content
- [ ] Post to LinkedIn
- [ ] Consider adding relevant hashtags
- [ ] Monitor engagement

## Purpose
Daily business tips to help followers improve productivity and grow their businesses.

---
*Generated by AI Employee Scheduler - Morning Tip for {day_of_week.title()}*
"""

            tip_path.write_text(tip_content)
            logger.info(f"Morning tip created: {tip_filename}")

        except Exception as e:
            logger.error(f"Error posting morning tip for {day_of_week}: {e}")

    def run_weekly_audit(self):
        """Run weekly system audit."""
        try:
            logger.info("Running weekly audit...")

            # Create audit report
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            audit_filename = f"WEEKLY_AUDIT_{timestamp}.md"
            audit_path = self.needs_action_dir / audit_filename

            # Gather system metrics
            needs_action_count = len(list(self.needs_action_dir.glob('*.md')))
            scheduled_posts_count = len(list(self.scheduled_posts_dir.glob('*.json')))

            audit_content = f"""---
type: weekly_system_audit
date: {datetime.now().strftime('%Y-%m-%d')}
week_number: {datetime.now().isocalendar()[1]}
status: pending
---

# Weekly System Audit Report
Week ending: {datetime.now().strftime('%A, %B %d, %Y')}

## System Performance
- **Files processed this week:** [To be calculated by system]
- **Tasks completed:** [To be calculated by system]
- **Average response time:** [To be calculated by system]
- **System uptime:** [To be calculated by system]

## Current Metrics
- **Pending tasks in Needs_Action:** {needs_action_count}
- **Scheduled posts:** {scheduled_posts_count}
- **Active watchers running:** [To be verified by system]

## Recommendations
- Review performance metrics
- Consider system improvements
- Update Company_Handbook.md if needed

## Follow-up Items
- [ ] Review pending tasks
- [ ] Update system documentation
- [ ] Plan improvements for next week
- [ ] Check watcher scripts status

---
*Generated by AI Employee Scheduler - Weekly Audit*
"""

            audit_path.write_text(audit_content)
            logger.info(f"Weekly audit report created: {audit_filename}")

        except Exception as e:
            logger.error(f"Error running weekly audit: {e}")

    def run_continuous_scheduler(self):
        """Run the scheduler continuously."""
        # Set up default schedules
        self.schedule_daily_tasks()
        self.schedule_linkedin_posts()

        logger.info("Starting continuous task scheduler...")

        while True:
            try:
                # Run pending scheduled tasks
                schedule.run_pending()

                # Wait for 60 seconds before checking again
                time.sleep(60)

            except KeyboardInterrupt:
                logger.info("Scheduler stopped by user")
                break
            except Exception as e:
                logger.error(f"Error in scheduler: {e}")
                # Wait before retrying to avoid rapid error loops
                time.sleep(60)

def main():
    """Main function to demonstrate scheduler functionality."""
    try:
        scheduler = TaskScheduler()

        # Schedule sample tasks
        scheduler.schedule_daily_tasks()
        scheduler.schedule_linkedin_posts()

        print("Scheduler configured with daily and weekly tasks:")
        print("- Daily status report at 09:00")
        print("- Daily cleanup at 23:00")
        print("- LinkedIn posting at 12:00")
        print("- Weekly audit at Sunday 22:00")
        print("- Morning business tips Mon-Fri at 09:00")

        # Run a sample task manually to demonstrate
        scheduler.run_daily_status_report()
        print("Sample daily status report generated")

        scheduler.post_morning_tip("monday")
        print("Sample morning tip generated")

        print("\nScheduler is ready to run tasks automatically.")
        print("To run continuously, call scheduler.run_continuous_scheduler()")

    except Exception as e:
        logger.error(f"Error in scheduler demo: {e}")

if __name__ == "__main__":
    main()